// frontend/src/components/ProviderCard.vue
<template>
  <div class="provider-card">
    <h3>{{ provider.name }}</h3>
    <div>Type: {{ provider.type }}</div>
    <span :class="['status', provider.status]">{{ provider.status }}</span>
  </div>
</template>

<script setup lang="ts">
defineProps<{
  provider: {
    name: string
    type: string
    status: string
  }
}>()
</script>

<style scoped>
.provider-card {
  border: 1px solid #ccc;
  border-radius: 8px;
  padding: 12px;
  margin-bottom: 10px;
}
.status.healthy {
  color: green;
}
.status.degraded {
  color: orange;
}
.status.error,
.status.failed {
  color: red;
}
</style>

// frontend/src/components/ProviderCard.tsx
import React from "react";
import { Card, CardContent, Typography, Chip } from "@mui/material";

interface Provider {
  name: string;
  type: string;
  status: string;
}

const ProviderCard: React.FC<{ provider: Provider }> = ({ provider }) => (
  <Card variant="outlined" sx={{ mb: 2 }}>
    <CardContent>
      <Typography variant="h6">{provider.name}</Typography>
      <Typography variant="body2" color="text.secondary">
        Type: {provider.type}
      </Typography>
      <Chip
        label={provider.status}
        color={
          provider.status === "healthy"
            ? "success"
            : provider.status === "degraded"
            ? "warning"
            : "error"
        }
        sx={{ mt: 1 }}
      />
    </CardContent>
  </Card>
);

export default ProviderCard;
