// frontend/src/pages/Providers.vue
<template>
  <div>
    <h1>Providers</h1>
    <div v-if="loading">
      <span>Loading...</span>
    </div>
    <div v-else>
      <ProviderCard v-for="p in providers" :key="p.name" :provider="p" />
      <div v-if="!providers.length">No providers available</div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import ProviderCard from '@components/ProviderCard.vue'

interface Provider {
  name: string
  type: string
  status: string
}

const loading = ref(true)
const providers = ref<Provider[]>([])

onMounted(async () => {
  loading.value = true
  try {
    const res = await fetch('/api/providers')
    const data = await res.json()
    providers.value = data.providers ?? []
  } finally {
    loading.value = false
  }
})
</script>

// frontend/src/pages/Providers.tsx
import React, { useEffect, useState } from "react";
import { Container, Typography, Grid, CircularProgress } from "@mui/material";
import ProviderCard from "@components/ProviderCard";

interface Provider {
  name: string;
  type: string;
  status: string;
}

const Providers: React.FC = () => {
  const [providers, setProviders] = useState<Provider[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch("/api/providers")
      .then((r) => r.json())
      .then((data) => setProviders(data.providers ?? []))
      .finally(() => setLoading(false));
  }, []);

  return (
    <Container maxWidth="md" sx={{ mt: 4 }}>
      <Typography variant="h4" gutterBottom>
        Providers
      </Typography>
      {loading ? (
        <CircularProgress />
      ) : (
        <Grid container spacing={2}>
          {providers.map((provider) => (
            <Grid item xs={12} md={6} key={provider.name}>
              <ProviderCard provider={provider} />
            </Grid>
          ))}
        </Grid>
      )}
    </Container>
  );
};

export default Providers;
